"""initial schema

Revision ID: b9647b071e5c
Revises: 
Create Date: 2026-09-16 19:22:53.971759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9647b071e5c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS warehouse")
    op.create_table('brands',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('brand_id', name=op.f('pk_brands')),
    sa.UniqueConstraint('brand_name', name=op.f('uq_brands_brand_name'))
    )
    op.create_table('campaigns',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('campaign_name', sa.String(length=200), nullable=False),
    sa.Column('campaign_type', sa.String(length=100), nullable=False),
    sa.Column('budget', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('campaign_id', name=op.f('pk_campaigns'))
    )
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('parent_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_category_id'], ['categories.category_id'], name=op.f('fk_categories_parent_category_id_categories')),
    sa.PrimaryKeyConstraint('category_id', name=op.f('pk_categories'))
    )
    op.create_table('payment_methods',
    sa.Column('payment_method_id', sa.Integer(), nullable=False),
    sa.Column('method_name', sa.String(length=100), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=True),
    sa.Column('method_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('payment_method_id', name=op.f('pk_payment_methods'))
    )
    op.create_table('permissions',
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('permission_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('permission_id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('permission_name', name=op.f('uq_permissions_permission_name'))
    )
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('role_id', name=op.f('pk_roles')),
    sa.UniqueConstraint('role_name', name=op.f('uq_roles_role_name'))
    )
    op.create_table('shipping_carriers',
    sa.Column('carrier_id', sa.Integer(), nullable=False),
    sa.Column('carrier_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('carrier_id', name=op.f('pk_shipping_carriers')),
    sa.UniqueConstraint('carrier_name', name=op.f('uq_shipping_carriers_carrier_name'))
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('account_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('warehouses',
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_name', sa.String(length=150), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('warehouse_id', name=op.f('pk_warehouses'))
    )
    op.create_table('audit_logs',
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('audit_id', name=op.f('pk_audit_logs'))
    )
    op.create_table('customers',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('customer_status', sa.String(length=50), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('last_order_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_customers_user_id_users')),
    sa.PrimaryKeyConstraint('customer_id', name=op.f('pk_customers')),
    sa.UniqueConstraint('user_id', name=op.f('uq_customers_user_id'))
    )
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.brand_id'], name=op.f('fk_products_brand_id_brands')),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk_products'))
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.permission_id'], name=op.f('fk_role_permissions_permission_id_permissions')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], name=op.f('fk_role_permissions_role_id_roles')),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('shipping_methods',
    sa.Column('shipping_method_id', sa.Integer(), nullable=False),
    sa.Column('carrier_id', sa.Integer(), nullable=False),
    sa.Column('method_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['shipping_carriers.carrier_id'], name=op.f('fk_shipping_methods_carrier_id_shipping_carriers')),
    sa.PrimaryKeyConstraint('shipping_method_id', name=op.f('pk_shipping_methods'))
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], name=op.f('fk_user_roles_role_id_roles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_user_roles_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('campaign_products',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.campaign_id'], name=op.f('fk_campaign_products_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name=op.f('fk_campaign_products_product_id_products')),
    sa.PrimaryKeyConstraint('campaign_id', 'product_id', name=op.f('pk_campaign_products'))
    )
    op.create_table('customer_addresses',
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('address_type', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('fk_customer_addresses_customer_id_customers')),
    sa.PrimaryKeyConstraint('address_id', name=op.f('pk_customer_addresses'))
    )
    op.create_table('customer_campaigns',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('interaction_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.campaign_id'], name=op.f('fk_customer_campaigns_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('fk_customer_campaigns_customer_id_customers')),
    sa.PrimaryKeyConstraint('customer_id', 'campaign_id', name=op.f('pk_customer_campaigns'))
    )
    op.create_table('customer_events',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('fk_customer_events_customer_id_customers')),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_customer_events'))
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('order_status', sa.String(length=50), nullable=False),
    sa.Column('subtotal_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shipping_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('fk_orders_customer_id_customers')),
    sa.PrimaryKeyConstraint('order_id', name=op.f('pk_orders'))
    )
    op.create_table('product_categories',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], name=op.f('fk_product_categories_category_id_categories')),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name=op.f('fk_product_categories_product_id_products')),
    sa.PrimaryKeyConstraint('product_id', 'category_id', name=op.f('pk_product_categories'))
    )
    op.create_table('product_variants',
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name=op.f('fk_product_variants_product_id_products')),
    sa.PrimaryKeyConstraint('variant_id', name=op.f('pk_product_variants')),
    sa.UniqueConstraint('sku', name=op.f('uq_product_variants_sku'))
    )
    op.create_table('campaign_conversions',
    sa.Column('conversion_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('attribution_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.campaign_id'], name=op.f('fk_campaign_conversions_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('fk_campaign_conversions_customer_id_customers')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], name=op.f('fk_campaign_conversions_order_id_orders')),
    sa.PrimaryKeyConstraint('conversion_id', name=op.f('pk_campaign_conversions'))
    )
    op.create_table('inventory',
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('quantity_on_hand', sa.Integer(), nullable=False),
    sa.Column('quantity_reserved', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.variant_id'], name=op.f('fk_inventory_variant_id_product_variants')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.warehouse_id'], name=op.f('fk_inventory_warehouse_id_warehouses')),
    sa.PrimaryKeyConstraint('inventory_id', name=op.f('pk_inventory'))
    )
    op.create_table('inventory_transactions',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('quantity_change', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.variant_id'], name=op.f('fk_inventory_transactions_variant_id_product_variants')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.warehouse_id'], name=op.f('fk_inventory_transactions_warehouse_id_warehouses')),
    sa.PrimaryKeyConstraint('transaction_id', name=op.f('pk_inventory_transactions'))
    )
    op.create_table('order_items',
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], name=op.f('fk_order_items_order_id_orders')),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.variant_id'], name=op.f('fk_order_items_variant_id_product_variants')),
    sa.PrimaryKeyConstraint('order_item_id', name=op.f('pk_order_items'))
    )
    op.create_table('order_status_history',
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], name=op.f('fk_order_status_history_order_id_orders')),
    sa.PrimaryKeyConstraint('history_id', name=op.f('pk_order_status_history'))
    )
    op.create_table('payments',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('payment_method_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=50), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('transaction_reference', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], name=op.f('fk_payments_order_id_orders')),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.payment_method_id'], name=op.f('fk_payments_payment_method_id_payment_methods')),
    sa.PrimaryKeyConstraint('payment_id', name=op.f('pk_payments'))
    )
    op.create_table('shipments',
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('shipping_method_id', sa.Integer(), nullable=False),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('shipment_status', sa.String(length=50), nullable=False),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], name=op.f('fk_shipments_order_id_orders')),
    sa.ForeignKeyConstraint(['shipping_method_id'], ['shipping_methods.shipping_method_id'], name=op.f('fk_shipments_shipping_method_id_shipping_methods')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.warehouse_id'], name=op.f('fk_shipments_warehouse_id_warehouses')),
    sa.PrimaryKeyConstraint('shipment_id', name=op.f('pk_shipments'))
    )
    op.create_table('refunds',
    sa.Column('refund_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('refund_status', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.payment_id'], name=op.f('fk_refunds_payment_id_payments')),
    sa.PrimaryKeyConstraint('refund_id', name=op.f('pk_refunds'))
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('fk_reviews_customer_id_customers')),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.order_item_id'], name=op.f('fk_reviews_order_item_id_order_items')),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name=op.f('fk_reviews_product_id_products')),
    sa.PrimaryKeyConstraint('review_id', name=op.f('pk_reviews'))
    )
    op.create_table('shipment_items',
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.order_item_id'], name=op.f('fk_shipment_items_order_item_id_order_items')),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.shipment_id'], name=op.f('fk_shipment_items_shipment_id_shipments')),
    sa.PrimaryKeyConstraint('shipment_id', 'order_item_id', name=op.f('pk_shipment_items'))
    )
    op.create_table('dim_campaign',
    sa.Column('campaign_key', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('campaign_name', sa.String(length=200), nullable=False),
    sa.Column('campaign_type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('campaign_key'),
    schema='warehouse'
    )
    op.create_table('dim_category',
    sa.Column('category_key', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('parent_category_name', sa.String(length=100), nullable=True),
    sa.Column('top_level_category', sa.String(length=100), nullable=False),
    sa.Column('category_level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('category_key'),
    schema='warehouse'
    )
    op.create_table('dim_customer',
    sa.Column('customer_key', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('customer_status', sa.String(length=50), nullable=False),
    sa.Column('effective_start_date', sa.Date(), nullable=False),
    sa.Column('effective_end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('customer_key'),
    schema='warehouse'
    )
    op.create_table('dim_date',
    sa.Column('date_key', sa.Integer(), nullable=False),
    sa.Column('full_date', sa.Date(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('month_name', sa.String(length=20), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('date_key'),
    schema='warehouse'
    )
    op.create_table('dim_product',
    sa.Column('product_key', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('brand_name', sa.String(length=100), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('product_key'),
    schema='warehouse'
    )
    op.create_table('fact_customer_activity',
    sa.Column('activity_key', sa.Integer(), nullable=False),
    sa.Column('date_key', sa.Integer(), nullable=False),
    sa.Column('customer_key', sa.Integer(), nullable=False),
    sa.Column('product_key', sa.Integer(), nullable=True),
    sa.Column('campaign_key', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('activity_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_key'], ['warehouse.dim_campaign.campaign_key'], ),
    sa.ForeignKeyConstraint(['customer_key'], ['warehouse.dim_customer.customer_key'], ),
    sa.ForeignKeyConstraint(['date_key'], ['warehouse.dim_date.date_key'], ),
    sa.ForeignKeyConstraint(['product_key'], ['warehouse.dim_product.product_key'], ),
    sa.PrimaryKeyConstraint('activity_key'),
    schema='warehouse'
    )
    op.create_table('fact_inventory_snapshot',
    sa.Column('snapshot_key', sa.Integer(), nullable=False),
    sa.Column('date_key', sa.Integer(), nullable=False),
    sa.Column('product_key', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('quantity_on_hand', sa.Integer(), nullable=False),
    sa.Column('quantity_reserved', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['date_key'], ['warehouse.dim_date.date_key'], ),
    sa.ForeignKeyConstraint(['product_key'], ['warehouse.dim_product.product_key'], ),
    sa.PrimaryKeyConstraint('snapshot_key'),
    schema='warehouse'
    )
    op.create_table('fact_sales',
    sa.Column('sales_key', sa.Integer(), nullable=False),
    sa.Column('date_key', sa.Integer(), nullable=False),
    sa.Column('customer_key', sa.Integer(), nullable=False),
    sa.Column('product_key', sa.Integer(), nullable=False),
    sa.Column('category_key', sa.Integer(), nullable=False),
    sa.Column('campaign_key', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('profit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['campaign_key'], ['warehouse.dim_campaign.campaign_key'], ),
    sa.ForeignKeyConstraint(['category_key'], ['warehouse.dim_category.category_key'], ),
    sa.ForeignKeyConstraint(['customer_key'], ['warehouse.dim_customer.customer_key'], ),
    sa.ForeignKeyConstraint(['date_key'], ['warehouse.dim_date.date_key'], ),
    sa.ForeignKeyConstraint(['product_key'], ['warehouse.dim_product.product_key'], ),
    sa.PrimaryKeyConstraint('sales_key'),
    schema='warehouse'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact_sales', schema='warehouse')
    op.drop_table('fact_inventory_snapshot', schema='warehouse')
    op.drop_table('fact_customer_activity', schema='warehouse')
    op.drop_table('dim_product', schema='warehouse')
    op.drop_table('dim_date', schema='warehouse')
    op.drop_table('dim_customer', schema='warehouse')
    op.drop_table('dim_category', schema='warehouse')
    op.drop_table('dim_campaign', schema='warehouse')
    op.drop_table('shipment_items')
    op.drop_table('reviews')
    op.drop_table('refunds')
    op.drop_table('shipments')
    op.drop_table('payments')
    op.drop_table('order_status_history')
    op.drop_table('order_items')
    op.drop_table('inventory_transactions')
    op.drop_table('inventory')
    op.drop_table('campaign_conversions')
    op.drop_table('product_variants')
    op.drop_table('product_categories')
    op.drop_table('orders')
    op.drop_table('customer_events')
    op.drop_table('customer_campaigns')
    op.drop_table('customer_addresses')
    op.drop_table('campaign_products')
    op.drop_table('user_roles')
    op.drop_table('shipping_methods')
    op.drop_table('role_permissions')
    op.drop_table('products')
    op.drop_table('customers')
    op.drop_table('audit_logs')
    op.drop_table('warehouses')
    op.drop_table('users')
    op.drop_table('shipping_carriers')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('payment_methods')
    op.drop_table('categories')
    op.drop_table('campaigns')
    op.drop_table('brands')
    # ### end Alembic commands ###
